### PR TITLE
Small cosmetics, big change to repl input

### PR DESCRIPTION
**Pull request by sirlensalot**
Basically couldn't live with the "Evaluate" button :). Would be nice if focus immediately dropped into the textInput. Otherwise seems to work well!

### CODE REVIEW

**Comment by mightybyte** [comment]
@slpopejoy I like the idea here but I don't like the usability of the really small area that you have to click on to put the repl in focus.  I just pushed a commit that fixes that.  Take a look  at how that works and let me know what you think.

**Comment by sirlensalot** [comment]
I like it. Let's merge this and then get ready to bring in the official 2.4 release when its ready, sound good?

**Comment by sirlensalot** [comment]
Also, what about closure compiler? (not for this PR)

**Comment by mightybyte** [comment]
Yeah, we can definitely set up the closure compiler and gzip.  But that might be more appropriate to do in the website.

**Review by mightybyte — APPROVED** [review]

**Pull request merged**
